version: "3.8"
services:
  backend:
    image: sachethk/second-brain-backend:latest
    env_file:
      - ./backend/.env
    # Ports are not needed if we use the internal network via nginx proxy
    # ports:
    #   - "3002:3002"

  frontend:
    image: sachethk/second-brain-frontend:latest
    ports:
      - "80:80"